## Integrate with Local VS Code

In [6]:
from google.colab import drive
drive.mount("/content/drive")

ModuleNotFoundError: No module named 'google'

In [ ]:
!pip install colab_ssh --upgrade

In [ ]:
from colab_ssh import launch_ssh_cloudflared, init_git_cloudflared

ModuleNotFoundError: No module named 'apt'

In [ ]:
launch_ssh_cloudflared('1014SBFmGz')
init_git_cloudflared(repository_url="https://github.com/SS-Runen/Collab-VSCode-Integration-Demo.git",
         personal_token="vuIC4fCR+Ron3PMZlL/wHuR95ZLKKZXwm27eY/pOycM",
         branch="main",
         email="dd39bc@gmail.com",
         username="SS-Runen")

NameError: name 'launch_ssh_cloudflared' is not defined

## Matrix and Vector Multiplication

In [ ]:
import numpy as np
import sklearn

In [ ]:
matrix_a = np.array([[3, 4, 2]])
matrix_b = np.array([[13,9,7,15],[8,7,4,6], [6,4,0,3]])

In [ ]:
np.matmul(matrix_a, matrix_b)

array([[83, 63, 37, 75]])

In [ ]:
vector_a = [1, 2, 3]
vector_b = [2, 4, 6]

In [ ]:
np.dot(vector_a, vector_b)

28

In [ ]:
np.dot(np.transpose(vector_a), vector_b)

28

## Transfer Train Data into DataFrame


In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df_mnist_train_small = pd.DataFrame(data=pd.read_csv("../content/sample_data/mnist_train_small.csv"))
df_mnist_train_small.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
df_mnist_train_small.shape

(19999, 785)

## Neural Network: SoftMax Activation vs. ReLU Activation
Compare the accuracy of a neural network with ReLU activations for the hidden layer vs. one with Sigmoid activations for the hidden layer.

**About the MNIST Handwritten Digit Data**

Every line of these files consists of an image, i.e. numbers between 0 and 9. The first number of each line is the label, i.e. the digit which is depicted in the image. The following 784 numbers are the pixels of the 28 x 28 image.

In [ ]:
df_mnist_train_small.iloc[: , : ].head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

### Train Model with SoftMax Activations

In [ ]:
from tensorflow.keras.losses import CategoricalCrossentropy

In [ ]:
model_neuralnet_softmax = Sequential([
    Dense(units=25, activation="softmax"),
    Dense(units=15, activation="softmax"),
    Dense(units=10, activation="softmax"),
])

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [ ]:
model_neuralnet_softmax.compile(loss=SparseCategoricalCrossentropy())
model_neuralnet_softmax.fit(df_mnist_train_small.iloc[: , 1:], df_mnist_train_small.iloc[: , 0:1], epochs=128)

Epoch 1/128
625/625 [==============================] - 2s 2ms/step - loss: 2.2438
Epoch 2/128
625/625 [==============================] - 2s 4ms/step - loss: 1.9921
Epoch 3/128
625/625 [==============================] - 2s 3ms/step - loss: 1.6281
Epoch 4/128
625/625 [==============================] - 3s 5ms/step - loss: 1.3763
Epoch 5/128
625/625 [==============================] - 3s 5ms/step - loss: 1.2427
Epoch 6/128
625/625 [==============================] - 2s 4ms/step - loss: 1.1938
Epoch 7/128
625/625 [==============================] - 2s 3ms/step - loss: 1.1764
Epoch 8/128
625/625 [==============================] - 2s 3ms/step - loss: 1.1665
Epoch 9/128
625/625 [==============================] - 1s 2ms/step - loss: 1.1661
Epoch 10/128
625/625 [==============================] - 1s 2ms/step - loss: 1.1502
Epoch 11/128
625/625 [==============================] - 2s 3ms/step - loss: 1.1415
Epoch 12/128
625/625 [==============================] - 1s 2ms/step - loss: 1.1409
Epoch 13/128


### Train Model with ReLU Activations

In [ ]:
# Using a ReLU as the output layer activation function results in a loss of nan, i.e. not a number.
model_neuralnet_relu = Sequential([
    Dense(units=25, activation="relu"),
    Dense(units=15, activation="relu"),
    Dense(units=10, activation="softmax"),
])

In [ ]:
model_neuralnet_relu.compile(loss=SparseCategoricalCrossentropy())
model_neuralnet_relu.fit(df_mnist_train_small.iloc[: , 1: ], df_mnist_train_small.iloc[: , 0:1], epochs=128)

Epoch 1/128
625/625 [==============================] - 2s 2ms/step - loss: 2.3452
Epoch 2/128
625/625 [==============================] - 1s 2ms/step - loss: 1.6744
Epoch 3/128
625/625 [==============================] - 1s 2ms/step - loss: 1.5424
Epoch 4/128
625/625 [==============================] - 1s 2ms/step - loss: 1.3692
Epoch 5/128
625/625 [==============================] - 1s 2ms/step - loss: 1.2011
Epoch 6/128
625/625 [==============================] - 2s 3ms/step - loss: 1.1410
Epoch 7/128
625/625 [==============================] - 2s 3ms/step - loss: 1.0949
Epoch 8/128
625/625 [==============================] - 1s 2ms/step - loss: 1.0594
Epoch 9/128
625/625 [==============================] - 1s 2ms/step - loss: 1.0365
Epoch 10/128
625/625 [==============================] - 1s 2ms/step - loss: 1.0047
Epoch 11/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9938
Epoch 12/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9691
Epoch 13/128


In [ ]:
df_mnist_test = pd.DataFrame(data=pd.read_csv("../content/sample_data/mnist_test.csv"))
df_mnist_test.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
y_pred_sm = model_neuralnet_softmax.predict(x=df_mnist_test.iloc[: , 1: ])
y_pred_sm[0:5]

313/313 [==============================] - 1s 1ms/step


array([[4.2111338e-03, 5.6765713e-03, 9.3937123e-01, 1.5223025e-02,
        5.1115216e-03, 6.0248524e-03, 6.8350583e-03, 5.9587876e-03,
        9.1729742e-03, 2.4148435e-03],
       [3.9886075e-04, 9.8952425e-01, 3.8146664e-04, 8.2696881e-04,
        1.0801606e-03, 7.8799709e-04, 9.0000074e-04, 6.3380931e-04,
        4.8605762e-03, 6.0577446e-04],
       [4.3372521e-01, 1.5357567e-03, 1.7934982e-02, 8.0569722e-03,
        1.5213325e-02, 2.0409962e-02, 4.7752351e-01, 3.5350425e-03,
        1.5908549e-02, 6.1566862e-03],
       [1.1404683e-03, 1.0016854e-03, 6.0958369e-03, 4.6608318e-03,
        3.0219549e-01, 4.5065442e-03, 2.3797401e-03, 3.4579462e-01,
        7.6706181e-03, 3.2455415e-01],
       [3.9886075e-04, 9.8952425e-01, 3.8146664e-04, 8.2696881e-04,
        1.0801606e-03, 7.8799709e-04, 9.0000074e-04, 6.3380931e-04,
        4.8605762e-03, 6.0577446e-04]], dtype=float32)

In [ ]:
y_pred_relu = model_neuralnet_relu.predict(x=df_mnist_test.iloc[ : , 1: ])
y_pred_relu[0:5]

313/313 [==============================] - 1s 1ms/step


array([[0.0000000e+00, 0.0000000e+00, 9.9999994e-01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 9.9999994e-01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.3355474e-01, 5.6943242e-03, 1.5347790e-02, 1.9699648e-02,
        2.2792579e-01, 1.7620359e-02, 9.5961504e-03, 8.3035091e-03,
        2.2520918e-01, 2.3704861e-01],
       [2.3355474e-01, 5.6943242e-03, 1.5347790e-02, 1.9699648e-02,
        2.2792579e-01, 1.7620359e-02, 9.5961504e-03, 8.3035091e-03,
        2.2520918e-01, 2.3704861e-01],
       [0.0000000e+00, 9.9999994e-01, 7.0970976e-23, 2.5499343e-26,
        9.6644416e-34, 2.2096965e-28, 5.5395288e-24, 1.8761910e-19,
        2.6946878e-17, 4.1029635e-36]], dtype=float32)

In [ ]:
df_mnist_test.iloc[ : , 0:1].head()

7
0  2
1  1
2  0
3  4
4  1

## Recommended Implementation of Softmax Digit Classifier Neural Network

Use a linear activation function. This is the input (z) to the Sparse Categorical Cross Entropy function, with will take z values and apply the loss function.

In [ ]:
model_neuralnet_softmax_fromlogits = Sequential([
    Dense(units=25, activation="softmax"),
    Dense(units=15, activation="softmax"),
    Dense(units=10, activation="linear"),
])
model_neuralnet_softmax_fromlogits.compile(loss=SparseCategoricalCrossentropy(from_logits=True))
model_neuralnet_softmax_fromlogits.fit(df_mnist_train_small.iloc[: , 1:], df_mnist_train_small.iloc[: , 0:1], epochs=128)

Epoch 1/128
625/625 [==============================] - 2s 2ms/step - loss: 2.2668
Epoch 2/128
625/625 [==============================] - 1s 2ms/step - loss: 2.0718
Epoch 3/128
625/625 [==============================] - 1s 2ms/step - loss: 1.7365
Epoch 4/128
625/625 [==============================] - 1s 2ms/step - loss: 1.4234
Epoch 5/128
625/625 [==============================] - 2s 3ms/step - loss: 1.2126
Epoch 6/128
625/625 [==============================] - 2s 3ms/step - loss: 1.0764
Epoch 7/128
625/625 [==============================] - 1s 2ms/step - loss: 1.0298
Epoch 8/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9958
Epoch 9/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9891
Epoch 10/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9755
Epoch 11/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9768
Epoch 12/128
625/625 [==============================] - 1s 2ms/step - loss: 0.9304
Epoch 13/128


In [ ]:
y_pred_sm_fl = model_neuralnet_softmax_fromlogits.predict(x=df_mnist_test.iloc[: , 1: ])
y_pred_sm_fl[0:5]

313/313 [==============================] - 1s 2ms/step


array([[-7.977519 , -7.3009605, -1.8617551, -5.825162 , -7.0901337,
        -7.3500814, -7.749252 , -6.5411634, -6.278128 , -7.554934 ],
       [-8.9719515, -0.7973647, -8.0392885, -8.136113 , -8.296127 ,
        -8.130465 , -8.784258 , -7.274671 , -5.7105575, -8.092766 ],
       [-0.1974017, -7.898847 , -6.0210567, -6.4967723, -7.2417   ,
        -5.5600104, -6.6175685, -6.16318  , -6.102816 , -5.8052716],
       [-7.7342477, -6.736892 , -4.9645824, -5.812826 , -1.1919194,
        -5.3826656, -6.06262  , -4.1092443, -5.6098156, -1.2057298],
       [-8.9719515, -0.7973647, -8.0392885, -8.136113 , -8.296127 ,
        -8.130465 , -8.784258 , -7.274671 , -5.7105575, -8.092766 ]],
      dtype=float32)

In [ ]:
model_neuralnet_relu_fromlogits = Sequential([
    Dense(units=25, activation="relu"),
    Dense(units=15, activation="relu"),
    Dense(units=10, activation="linear"),
])
model_neuralnet_relu_fromlogits.compile(loss=SparseCategoricalCrossentropy(from_logits=True))
model_neuralnet_relu_fromlogits.fit(df_mnist_train_small.iloc[: , 1:], df_mnist_train_small.iloc[: , 0:1], epochs=128)

Epoch 1/128
625/625 [==============================] - 2s 2ms/step - loss: 2.0273
Epoch 2/128
625/625 [==============================] - 1s 2ms/step - loss: 0.8883
Epoch 3/128
625/625 [==============================] - 1s 2ms/step - loss: 0.7462
Epoch 4/128
625/625 [==============================] - 1s 2ms/step - loss: 0.6551
Epoch 5/128
625/625 [==============================] - 1s 2ms/step - loss: 0.5836
Epoch 6/128
625/625 [==============================] - 1s 2ms/step - loss: 0.5222
Epoch 7/128
625/625 [==============================] - 1s 2ms/step - loss: 0.4633
Epoch 8/128
625/625 [==============================] - 2s 3ms/step - loss: 0.4445
Epoch 9/128
625/625 [==============================] - 2s 3ms/step - loss: 0.4127
Epoch 10/128
625/625 [==============================] - 1s 2ms/step - loss: 0.4052
Epoch 11/128
625/625 [==============================] - 1s 2ms/step - loss: 0.4002
Epoch 12/128
625/625 [==============================] - 1s 2ms/step - loss: 0.3879
Epoch 13/128


In [ ]:
y_pred_relu_fl = model_neuralnet_relu_fromlogits.predict(x=df_mnist_test.iloc[: , 1: ])
y_pred_sm_fl[0:5]

313/313 [==============================] - 1s 2ms/step


array([[-7.977519 , -7.3009605, -1.8617551, -5.825162 , -7.0901337,
        -7.3500814, -7.749252 , -6.5411634, -6.278128 , -7.554934 ],
       [-8.9719515, -0.7973647, -8.0392885, -8.136113 , -8.296127 ,
        -8.130465 , -8.784258 , -7.274671 , -5.7105575, -8.092766 ],
       [-0.1974017, -7.898847 , -6.0210567, -6.4967723, -7.2417   ,
        -5.5600104, -6.6175685, -6.16318  , -6.102816 , -5.8052716],
       [-7.7342477, -6.736892 , -4.9645824, -5.812826 , -1.1919194,
        -5.3826656, -6.06262  , -4.1092443, -5.6098156, -1.2057298],
       [-8.9719515, -0.7973647, -8.0392885, -8.136113 , -8.296127 ,
        -8.130465 , -8.784258 , -7.274671 , -5.7105575, -8.092766 ]],
      dtype=float32)

Softmax Activations:
Lowest without Logits: ~0.95. Lowest using Logits: ~0.87

ReLU with a Softmax output layer:
Lowest without Logits: ~0.86. Lowest using Logits: ~0.82.

## Compare Model Accuracy

In [ ]:
from sklearn.metrics import balanced_accuracy_score

The predictions are arrays of arrays. Each first-level array gives a list of probabilities that the input matches a certain label. These have to be translated into predicted integer values for the balanced accuracy scorer to work.

## Intuition for Derivatives

In [ ]:
import sympy

In [ ]:
J, w = sympy.symbols('J, w')

In [ ]:
J = w ** 2
J

w**2

In [ ]:
dJ_dw = sympy.diff(J, w)

In [ ]:
dJ_dw

2*w

In [ ]:
dJ_dw.subs([(w, 2)])

4

In [ ]:
J = w ** 3
dJ_dw = sympy.diff(J, w)
dJ_dw

3*w**2